FROM golang:1.18 AS build

WORKDIR /go/src/github.com/UserProblem/reposcanner
COPY engine ./engine
COPY go ./go
COPY models ./models
COPY main.go .
COPY go.mod .
COPY .env .

ENV CGO_ENABLED=0
RUN go get -d -v ./...

ENTRYPOINT ["go", "test", "-v", "./engine", "./go"]
