services:
  backend:
    build: ./
    secrets:
      - db-password
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=reposcanner
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    
  proxy:
    build: proxy
    ports:
      - 8080:8080
    depends_on: 
      - backend
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
