/*
 * Repository Secrets Scanner
 *
 * This is a simple backend API to allow a user to configure repositories for scanning, trigger a scan of those repositories, and retrieve the results.
 *
 * API version: 0.0.1
 * Contact: sean.critica@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"

	sw "github.com/UserProblem/reposcanner/go"
)

func main() {
	log.Printf("Server started")

	var app sw.App
	app.DBType = os.Getenv("DATABASE_TYPE")

	app.Initialize()
	app.Run()

	err := http.ListenAndServe(":8080", app.Router)

	app.CleanUp()
	log.Fatal(err.Error())
}
