/*
 * Repository Secrets Scanner
 *
 * This is a simple backend API to allow a user to configure repositories for scanning, trigger a scan of those repositories, and retrieve the results.
 *
 * API version: 0.0.1
 * Contact: sean.critica@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FindingsInfo struct {

	// type of security scan performed
	Type_ string `json:"type,omitempty"`

	// id of the security rule that produced this finding
	RuleId string `json:"ruleId,omitempty"`

	Location *FindingsLocation `json:"location,omitempty"`

	Metadata *FindingsMetadata `json:"metadata,omitempty"`
}
