/*
 * Repository Secrets Scanner
 *
 * This is a simple backend API to allow a user to configure repositories for scanning, trigger a scan of those repositories, and retrieve the results.
 *
 * API version: 0.0.1
 * Contact: sean.critica@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type FindingsMetadata struct {

	// description of the security vulnerability that produced this finding
	Description string `json:"description"`

	// classification of the security impact of this finding
	Severity string `json:"severity"`
}
