/*
 * Repository Secrets Scanner
 *
 * This is a simple backend API to allow a user to configure repositories for scanning, trigger a scan of those repositories, and retrieve the results.
 *
 * API version: 0.0.1
 * Contact: sean.critica@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type FileLocation struct {

	// the start of the block of code that produced this finding
	Begin interface{} `json:"begin"`

	// if present, the end of the block of code that produced this finding
	End interface{} `json:"end,omitempty"`
}
