/*
 * Repository Secrets Scanner
 *
 * This is a simple backend API to allow a user to configure repositories for scanning, trigger a scan of those repositories, and retrieve the results.
 *
 * API version: 0.0.1
 * Contact: sean.critica@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type PaginationParams struct {

	// start returning repositories from this position in the list
	Offset int32 `json:"offset,omitempty"`

	// maximum number of repositories to return per request
	PageSize int32 `json:"pageSize,omitempty"`
}

func (pp *PaginationParams) Clone() *PaginationParams {
	return &PaginationParams{
		Offset:   pp.Offset,
		PageSize: pp.PageSize,
	}
}
